name: docker-getting-started-app

services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    networks:
      - docker-getting-started-network
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    networks:
      docker-getting-started-network:
        aliases:
          - "mysql"
    volumes:
      - docker-getting-started-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  docker-getting-started-mysql-data:
    name: docker-getting-started-mysql-data

networks:
  docker-getting-started-network:
